name: Deploy QA edfx AWS Account

on:
  push:
    branches: [main]
    paths:
      - 'Aws-infra/tf_env/Qa_Edfx_Deployment.tfvars'
  pull_request:
    branches: [main]
    paths:
      - 'Aws-infra/tf_env/Qa_Edfx_Deployment.tfvars'
      - 'Aws-infra/tf_env/Qa_Backend_Edfx_Config.config'
  workflow_dispatch:
    inputs:
      Action:
        description: "Select Terraform Action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan

permissions:
  contents: read
  issues: write
  id-token: write

concurrency:
  group: tf-dev-${{ github.ref }}
  cancel-in-progress: false

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/Infra-Reusable-Template.yml
    with:
      environment: qa-edfx
      WORKING_DIR: Aws-infra/
      Terraform_Backend_Configuration_File: tf_env/Qa_Backend_Edfx_Config.config
      Terraform_Deployment_Configuration_File: tf_env/Qa_Edfx_Deployment.tfvars
      Action: ${{ github.event.inputs.Action == 'plan' && 'plan_only' || github.event.inputs.Action || (github.event_name == 'pull_request' && 'plan_only' || 'apply') }}
    secrets: inherit